<?php

/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="content-container col-12">
    <div class="header-banner">
        <img src="<?= $block->getViewFileUrl('images/siamsmile-main.png'); ?>" />
    </div>
    <br>
    <div class="row col-sm-12">
        <div class="col-sm-4 bg-get-off">
            <div style="padding-left:50%;padding-top:20%;padding-bottom:20%">
                <h6 style="color:orange">FREE GIFT</h6>
                <h4><b>NEW</b></h4>
                <h4><b>User</b></h4><br>
                <button class="shopnow-btn">SHOP NOW</button>
            </div>
        </div>
        <div class="col-sm-4 bg-get-off">
            <div style="padding-left:50%;padding-top:20%;padding-bottom:20%">
                <h6 style="color:orange">Geostrock</h6>
                <h4><b>Get 37%</b></h4>
                <h4><b>OFF</b></h4><br>
                <button class="shopnow-btn-grey">APPLY CODE</button>
            </div>
        </div>
        <div class="col-sm-4 bg-get-off">
            <div style="padding-left:50%;padding-top:20%;padding-bottom:20%">
                <h6 style="color:orange">Exclusive Design</h6>
                <h4><b>Minimal</b></h4>
                <h4><b>Chair</b></h4><br>
                <button class="shopnow-btn-grey">AVAIABLE</button>
            </div>
        </div>
    </div>
    <br>

    <div class="container col-12">
        <div class="row">
            <div class="col-sm bg-get-off">
                <img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" />
            </div>
            <div class="col-sm" style="background-color: #56DDC1;">
                <div class="text-center">
                    <h4 style="color:white">Makeup Kit</h4>
                    <h6 style="color:white">Lorem ipsum dolor sit amet,
                        adipisicing elit eius mod tem</h6>
                    <a class="shopnow-btn" href="#">READ ME</a>
                </div>
            </div>
            <div class="col-sm bg-get-off">
                <img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" />
            </div>
            <div class="col-sm" style="background-color: #56DDC1;">
                <div class="text-center">
                    <h4 style="color:white">Makeup Kit</h4>
                    <h6 style="color:white">Lorem ipsum dolor sit amet,
                        adipisicing elit eius mod tem</h6>
                    <a class="shopnow-btn" href="#">READ ME</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container col-12">
        <div class="row">
            <div class="col-sm" style="background-color: #56DDC1;">
                <div class="text-center">
                    <h4 style="color:white">Makeup Kit</h4>
                    <h6 style="color:white">Lorem ipsum dolor sit amet,
                        adipisicing elit eius mod tem</h6>
                    <a class="shopnow-btn" href="#">READ ME</a>
                </div>
            </div>
            <div class="col-sm bg-get-off">
                <img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" />
            </div>
            <div class="col-sm" style="background-color: #56DDC1;">
                <div class="text-center">
                    <h4 style="color:white">Makeup Kit</h4>
                    <h6 style="color:white">Lorem ipsum dolor sit amet,
                        adipisicing elit eius mod tem</h6>
                    <a class="shopnow-btn" href="#">READ ME</a>
                </div>
            </div>
            <div class="col-sm bg-get-off">
                <img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" />
            </div>
        </div>
    </div>
    <br>

    <div class="container col-12">
        <div class="p-5" style="background-color: grey;">
            <h1 style="color: white;"><strong>Newest Collection</strong></h1>
            <h1 style="color: white;"><strong>Lorem remlo</strong></h1>
            <h3 style="color: white;">Lorem</h3>
            <button>View All Collection</button>
        </div>
    </div>
    <br>

    <div class="container bootstrap snipets col-12">
        <h1 class="text-center text-muted">Featured collection</h1>
        <div class="row flow-offset-1">
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">
                            <del>$24.99</del></span><span class="price sale">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">
                            <del>$24.99</del></span><span class="price sale">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">
                            <del>$24.99</del></span><span class="price sale">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">
                            <del>$24.99</del></span><span class="price sale">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">
                            <del>$24.99</del></span><span class="price sale">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">
                            <del>$24.99</del></span><span class="price sale">$12.49</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-2 col-md-2 col-sm-4">
                <div class="product tumbnail thumbnail-3"><a href="#"><img src="<?= $block->getViewFileUrl('images/assassin.png'); ?>" alt=""></a>
                    <div class="caption">
                        <h6><a href="#">Short Sleeve T-Shirt</a></h6><span class="price">
                            <del>$24.99</del></span><span class="price sale">$12.49</span>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="gototop">
        <a href="#" class="action">Back to top</a>
    </div>
</div>